# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 63e6099d3c777779ad8ff37689daf23082b7ed6f3513079e5278ee80b31fc2fff009562617a1e48ec2d43fd029293726d84b2df728caccb131b576cf9884a2e3

test:
  secret_key_base: 917dae3bd93970eb370eac77633eada18addb1b3ea4cbf0b621889baff41b5de71b81892d487326927fced74e4062d795ef655f4a8a321751eb1e1872a0c00b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
